drop table if exists owners CASCADE;
drop table if exists pets CASCADE;
drop table if exists specialties CASCADE;
drop table if exists types CASCADE;
drop table if exists vet_specialties CASCADE;
drop table if exists vets CASCADE;
drop table if exists visits CASCADE;

create table owners
(
    id         integer generated by default as identity,
    first_name varchar(255),
    last_name  varchar(255),
    address    varchar(255),
    city       varchar(255),
    telephone  varchar(255),
    primary key (id)
);
create table pets
(
    id         integer generated by default as identity,
    name       varchar(255),
    birth_date date,
    owner_id   integer,
    type_id    integer,
    primary key (id)
);
create table specialties
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table types
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table vet_specialties
(
    vet_id       integer not null,
    specialty_id integer not null,
    primary key (vet_id, specialty_id)
);
create table vets
(
    id         integer generated by default as identity,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);
create table visits
(
    id             integer generated by default as identity,
    canceled_visit boolean,
    visit_date     date,
    description    varchar(255),
    pet_id         integer,
    vet_id         integer,
    primary key (id)
);
alter table pets
    add constraint FK6teg4kcjcnjhduguft56wcfoa foreign key (owner_id) references owners;
alter table pets
    add constraint FKtmmh1tq8pah5vxf8kuqqplo4p foreign key (type_id) references types;
alter table vet_specialties
    add constraint FK35uiboyrpfn1bndrr5jorcj0m foreign key (specialty_id) references specialties;
alter table vet_specialties
    add constraint FKby1c0fbaa0byaifi63vt18sx9 foreign key (vet_id) references vets;
alter table visits
    add constraint FK8036qgt84d8h5cckxrj952qoe foreign key (vet_id) references vets;
